# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-10-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('update_time', models.DateTimeField(verbose_name='时间')),
                ('province', models.CharField(default='无', max_length=15, verbose_name='省')),
                ('city', models.CharField(default='无', max_length=15, verbose_name='市')),
                ('confirm', models.IntegerField(default=0, verbose_name='累计确诊')),
                ('confirm_add', models.IntegerField(default=0, verbose_name='新增确诊')),
                ('heal', models.IntegerField(default=0, verbose_name='累计治愈')),
                ('dead', models.IntegerField(default=0, verbose_name='累计死亡')),
            ],
            options={
                'verbose_name': 'Details数据信息',
                'verbose_name_plural': 'Details数据信息',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('ds', models.DateTimeField(primary_key=True,verbose_name='时间')),
                ('confirm', models.IntegerField(default=0, verbose_name='累计确诊')),
                ('confirm_add', models.IntegerField(default=0, verbose_name='当日新增确诊')),
                ('suspect', models.IntegerField(default=0, verbose_name='剩余疑似')),
                ('suspect_add', models.IntegerField(default=0, verbose_name='当日新增疑似')),
                ('heal', models.IntegerField(default=0, verbose_name='累计治愈')),
                ('heal_add', models.IntegerField(default=0, verbose_name='当日累计治愈')),
                ('dead', models.IntegerField(default=0, verbose_name='累计死亡')),
                ('dead_add', models.IntegerField(default=0, verbose_name='当日累计死亡')),
            ],
            options={
                'verbose_name': 'History数据信息',
                'verbose_name_plural': 'History数据信息',
            },
        ),
    ]
